import { Dimensions, StyleSheet } from "react-native";

export const style = StyleSheet.create({
  mainConteiner: {
    top: 25,
    flex: 1,
  },
  escImg: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  logoX: {
    width: 40,
    height: 40,
    justifyContent: "center",
    marginLeft: 5,
  },
  optionsL: {
    marginBottom: 140,
    width: 60,
    height: 60,
    backgroundColor: "rgba(31, 224, 118, 0.61)",
    marginLeft: 35,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(31, 224, 118, 0.83)",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    resizeMode: "contain",
  },
  optionsR: {
    marginBottom: 140,
    width: 60,
    height: 60,
    marginRight: 35,
    backgroundColor: "rgba(224, 31, 31, 0.61)",
    marginLeft: 35,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(224, 31, 31, 0.83)",
    justifyContent: "center",
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    resizeMode: "contain",
  },
  options: {
    marginBottom: 80,
    width: 60,
    height: 60,
    resizeMode: "contain",
  },
  optionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    alignItems: "flex-end",
    marginBottom: 50,
    position: "relative",
  },
  locationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 5,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    top: 80,
    position: "absolute",
    maxWidth: Dimensions.get("window").width - 50,
    width: "auto",
  },
  locationText: {
    fontSize: 16,
    fontWeight: "medium",
    color: "white",
    // width: "100%",
    textAlign: "center",
  },

  // msalembe styles
  headerButtons: {
    marginTop: 25,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "85%",
    marginHorizontal: "auto",
  },
});
