import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const style = StyleSheet.create({
  mainConteiner: {
    flex: 1,
    paddingTop: 15,
    backgroundColor: "#fff",
  },
  logoX: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: height * 0.02,
    paddingHorizontal: width * 0.06,
  },
  logoImg: {
    width: width * 0.1,
    height: width * 0.1,
    resizeMode: "contain",
  },
  quizContainer: {
    flex: 1,
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: width * 0.06,
    paddingVertical: 20,
  },
  quizTitle: {
    fontSize: 20,
    fontWeight: "800",
    marginVertical: 20,
    color: "#7F1734",
  },
  quizDivider: {
    elevation: 6,
    shadowColor: "#7F1734",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    width: "95%",
    borderRadius: 12,
    backgroundColor: "#f5f5f5",
    padding: 18,
    alignSelf: "center",
  },
  quizQuestion: {
    fontSize: 16,
    color: "#333",
    marginBottom: 20,
    lineHeight: 22,
  },
  inputContainer: {
    marginTop: 16,
    width: "95%",
  },
  textInput: {
    elevation: 4,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderColor: "#dfdfdf",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: "#f0f0f0",
    color: "#000",
  },
  submitButton: {
    backgroundColor: "#7F1734",
    width: "95%",
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    marginBottom: 10,
  },
  submitText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 25,
    width: "85%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  },
  modalText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 22,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#7F1734",
  },
  editorTextInput: {
    width: "100%",
    height: 150,
    borderWidth: 1,
    borderColor: "#dfdfdf",
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    backgroundColor: "#f9f9f9",
    color: "#000",
    textAlignVertical: "top",
    marginBottom: 20,
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#aaa",
    paddingVertical: 10,
    marginRight: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  saveButton: {
    flex: 1,
    backgroundColor: "#7F1734",
    paddingVertical: 10,
    marginLeft: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  closeButton: {
    backgroundColor: "#7F1734",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginTop: 10, // usado no modal de boas-vindas
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
