import { StyleSheet, Dimensions } from "react-native";

export const style = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%'
  },
  meIcon: {
    width: 30,
    height: 30,
    resizeMode: "contain",
  },
  menuButton: {
    position: "absolute",
    top: 20,
    left: 15,
    backgroundColor: "white",
    padding: 18,
    borderRadius: 30,
    elevation: 8,
  },
  menuIcon: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
  recenterButton: {
    position: "absolute",
    bottom: 120,
    right: 15,
    backgroundColor: "white",
    padding: 10,
    borderRadius: 25,
    elevation: 3,
  },
  recenterIcon: {
    width: 30,
    height: 30,
    resizeMode: "contain",
  },
  sideMenu: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "80%",
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    paddingTop: 20,
    paddingHorizontal: 15,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  bottomMenu: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
  },
  menuItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  menuItemText: {
    marginLeft: 15,
    color: "#77767b",
    fontSize: 18,
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingBottom: 15,
    marginBottom: 10,
  },
  profileIcon: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  profileTextContainer: {
    flexDirection: "column",
  },
  profileName: {
    fontSize: 18,
    fontWeight: "600",
  },
  profileStatus: {
    fontSize: 14,
    color: "#777",
  },
  scrollView: {
    flex: 1,
  },
  contactContainer: {
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    paddingTop: 15,
    marginTop: 10,
    paddingHorizontal: 15,
  },
  contactTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  contactText: {
    fontSize: 14,
    color: "#444",
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    borderRadius: 1,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#fff',
    padding: 20,
    elevation: 6,
    borderTopWidth: 2,
    borderColor: '#ddd',
  },
  bottomBarItem: {
    alignItems: 'center',
  },
  bottomBarText: {
    fontSize: 10,
    color: '#77767b',
  },
});

 